name: Release for Replugged

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript and bundle into asar
        run: pnpm run rp

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "bundle/*, *.theme.css"
          makeLatest: true
          generateReleaseNotes: true